Фиксы ошибок
internal/client/client.go:142:21: response body must be closed
internal/client/client.go:23:2: rand.Seed has been deprecated since Go 1.20 and an alternative has been available since Go 1.0: As of Go 1.20 there is no reason to call Seed with a random value. Programs that call Seed with a known value to get a specific sequence of results should use New(NewSource(seed)) to obtain a local random generator.
Error: Process completed with exit code 1.